name: pedaki
services:
  db:
    image: mysql:8.2.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: pedaki
      MYSQL_DATABASE: pedaki
      MYSQL_USER: pedaki
      MYSQL_PASSWORD: pedaki
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
      - ./bin/init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    image: "ghcr.io/pedakihq/pedaki:$PEDAKI_TAG"
    depends_on:
      db:
        condition: service_healthy
      caddy:
        condition: service_healthy

  caddy:
    image: caddy:2.7.6
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    healthcheck:
      test: [ "CMD", "caddy", "version" ]
      timeout: 20s
      retries: 10

