name: pedaki_test
services:
  db:
    image: mysql:8.2.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: pedaki
      MYSQL_DATABASE: pedaki_test
      MYSQL_USER: pedaki
      MYSQL_PASSWORD: pedaki
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    ports:
      - 3306:3306
    volumes:
      - ./bin/init.sql:/docker-entrypoint-initdb.d/init.sql

