name: pedaki
services:
  db:
    image: mysql:8.2.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: pedaki
      MYSQL_DATABASE: pedaki
      MYSQL_USER: pedaki
      MYSQL_PASSWORD: pedaki
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  web:
      image: "ghcr.io/pedakihq/pedaki:$PEDAKI_APP_TAG"
      depends_on:
        db:
          condition: service_healthy

  caddy:
    image: caddy:2.7.5
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - web
