name: Deploy Script

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run script
        timeout-minutes: 3
        run: bash ./bin/deploy
        env:
          IS_CI: true
          WORKSPACE_DOMAIN: localhost
          WORKSPACE_NAME: demo
          PEDAKI_TAG: latest
          ADMIN_EMAIL: developers@pedaki.fr
          ADMIN_PASSWORD: password
          ADMIN_NAME: GitHub Actions
          EMAIL_DOMAIN: pedaki.fr
          QUERY_BATCH_SIZE: 100
