name: Code check

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Code check (lint)
    env:
      SKIP_ENV_VALIDATION: true
      NEXT_TELEMETRY_DISABLED: 1

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install deps
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build packages
        if: always()
        run: pnpm build --filter "./packages/*"

      - name: Run eslint
        if: always()
        run: pnpm lint

      - name: Run prettier
        if: always()
        run: pnpm format:check

      - name: Run typescript
        if: always()
        run: pnpm typecheck

      - name: Run build
        run: pnpm build


  test:
    name: Code check (test)
    env:
      SKIP_ENV_VALIDATION: true
      NEXT_TELEMETRY_DISABLED: 1

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install deps
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build packages
        if: always()
        run: pnpm build --filter "./packages/*"

      - name: Init database
        run: bash ./bin/init-test

      - name: Run tests
        run: pnpm test:coverage

      - name: 'Report Coverage'
        if: always() # Also generate the report if tests are failing
        uses: davelosert/vitest-coverage-report-action@v2
