name: Deploy Images to GHCR

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Image version
        required: true

jobs:
  push-app-image:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce permission requirement
        id: check-permissions
        uses: prince-chrismc/check-actor-permissions-action@v3
        with:
          permission: write

      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Inventory Image'
        run: scripts/release-ghcr.sh ${{github.event.inputs.version}}

