name: Release

on:
  push:
    tags:
      - v*

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      SKIP_ENV_VALIDATION: true

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Image and push to GHCR'
        run: bash ./scripts/release-ghcr.sh
        env:
          IMAGE_NAME: ghcr.io/pedakihq/pedaki
          DOCKERFILE: ./app/Dockerfile
